######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 21 04:58:19 2014
######################################################################

TEMPLATE = app
TARGET = 
QT += core gui
QT += widgets
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += ctmp3gui.c gui.c main.cpp mainwindow.cpp
